### ISSUE TITLE
task0中执行git pull staff main 命令报错

### ISSUE THREAD

**Issue by WellDown64** [ANA-IBD/docs#1]
@LAPTOP-GRM0ML3F MINGW64 ~/student12 (main)
$ git pull staff main
remote: Repository not found.
fatal: repository 'https://github.com/ANA-IBD/studen0.git/' not found
我根据教程设置了staff remote 但是还是不行

**Comment by abdtyx** [comment]
是https://github.com/ANA-IBD/student0.git/
你打错了，仔细看下

**Comment by WellDown64** [comment]
感谢回答，但是出现了新的问题
@LAPTOP-GRM0ML3F MINGW64 ~/student12 (main)
$git pull staff main
fatal: couldn't find remote ref main

**Comment by abdtyx** [comment]
git pull staff master
文档写错了，感谢反馈，我们会更新文档
